#!/bin/bash

set -e

LAST_BASE="$BASE_DIR"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Dependencies
sudo apt-get -y install confget
sudo cp -f "$BASE_DIR/confset.sh" /usr/local/bin/confset
sudo chmod a+x /usr/local/bin/confset

BASE_DIR="$LAST_BASE"