#!/bin/sh

sudo  rm -f "/opt/tomesh/nodestats-tomesh.py"
sudo systemctl disable node-exporter-ubiquiti.service
sudo systemctl stop node-exporter-ubiquiti.service
sudo rm -f /etc/systemd/system/node-exporter-ubiquiti.service
sudo systemctl daemon-reload
