#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MESH_NAME=$(confget -f /etc/mesh.conf -s general "mesh-name")

sudo apt-get install -y iw 

# Install bring-up script for the Mesh Point interface to /usr/bin
sudo cp "$BASE_DIR/mesh-point" /usr/bin/mesh-point

# Configure systemd to start mesh-point.service on system boot
sudo cp "$BASE_DIR/mesh-point.service" /etc/systemd/system/mesh-point.service
sudo chmod 644 /etc/systemd/system/mesh-point.service
sudo systemctl daemon-reload
sudo systemctl enable mesh-point.service
