#!/usr/bin/env bash

set -e

sudo apt-get install confget
systemctl enable systemd-networkd 

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Install bring-up script for the Mesh Point interface to /usr/bin

sudo cp "$BASE_DIR/85-wlan-mesh.network" "/etc/systemd/network/85-wlan-mesh.network"
sudo cp "8$BASE_DIR/5-wlan-mesh.link" "/etc/systemd/network/85-wlan-mesh.link"
sudo sed -i "s/##SSID##/$MESH_NAME/g" "/etc/systemd/network/85-wlan-mesh.link"
sudo cp "$BASE_DIR/50-mesh.rules" "/etc/udev/rules.d/50-mesh.rules"
sudo cp "$BASE_DIR/mesh.setup" "/usr/local/sbin/mesh.setup"
sudo chmod 644 /usr/local/sbin/mesh.setup


#stop network manager from processing wireless devices
if [ -z "$(cat /etc/NetworkManager/NetworkManager.conf | grep unmanaged-devices)" ]; then
	sudo echo "[keyfile]" >> /etc/NetworkManager/NetworkManager.conf
	sudo echo "unmanaged-devices=interface-name:wlan*" >> /etc/NetworkManager/NetworkManager.conf
fi

