#!/usr/bin/env bash

set -e

# Uninstall Mesh Point interfaces
sudo rm -f /etc/systemd/network/85-wlan-mesh.network
sudo rm -f /etc/systemd/network/85-wlan-mesh.link
sudo rm -f  /etc/udev/rules.d/50-mesh.rules
sudo rm -f /usr/local/sbin/mesh.setup
