#!/usr/bin/env bash

set -e

# Remove script and service
sudo systemctl disable peer-ipfs-bootstrap.service 2>/dev/null || true
sudo systemctl stop peer-ipfs-bootstrap.service 2>/dev/null || true
sudo systemctl daemon-reload
sudo rm -r /usr/local/bin/check-and-add-peers.sh
sudo rm -f /etc/systemd/system/peer-ipfs-bootstrap.service

# Uninstall dependencies
sudo apt-get remove jq
sudo npm uninstall -g cjdnstool
