#!/usr/bin/env bash

set -e

NODEJS_PREFIX=12
NODEJS_VERSION="$NODEJS_PREFIX.16.2"

# Check whether it has the newest version - 32-bit OSes need an older one
if [[ ("$(node --version)" != "v$NODEJS_VERSION") || ("$(uname -m)" =~ ^(i386|i586|i686)$ && "$(node --version)" != "v8.11.0") ]]; then
    # Check for armv6 and install an older LTS since 12 and later don't support this arch
    if uname -m | grep -Eq ^armv6; then
        wget -O /tmp/node-v10.20.0-linux-armv6l.tar.gz https://nodejs.org/dist/v10.20.0/node-v10.20.0-linux-armv6l.tar.gz
        sudo tar xfz /tmp/node-v10.20.0-linux-armv6l.tar.gz --strip 1 -C /
        rm -rf /tmp/node-v10.20.0-linux-armv6l.tar.gz
        sudo ln -s /bin/node /bin/nodejs
    # Check if it's 32-bit and install the previous NodeJS LTS since 10 and later doesn't support this arch
    elif [[ "$(uname -m)" =~ ^(i386|i586|i686)$ ]]; then
        wget -O /tmp/node-v8.16.0-linux-x86.tar.gz https://nodejs.org/dist/v8.11.0/node-v8.11.0-linux-x86.tar.gz
        sudo tar xfz /tmp/node-v8.11.0-linux-x86.tar.gz --strip 1 -C /
        rm -rf /tmp/node-v8.11.0-linux-x86.tar.gz
        sudo ln -s /bin/node /bin/nodejs
    else
        curl -sL https://deb.nodesource.com/setup_$NODEJS_PREFIX.x | sudo -E bash -
        sudo apt-get install -y nodejs
    fi
fi
