#!/usr/bin/env bash

set -e

LAST_BASE="$BASE_DIR"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if ! [[ -f "/bin/nodejs" ]]; then
    # Install older node.js manually if for older arm6 processor
    if ! [ "$(which nodejs)" ]; then
        # Check for armv6 and install nodejs manually instead since it will not install via repo
        if uname -m | grep -Eq ^armv6; then
            wget -O /tmp/node-v6.11.0-linux-armv6l.tar.gz https://nodejs.org/dist/v6.11.0/node-v6.11.0-linux-armv6l.tar.gz
            sudo tar xfz /tmp/node-v6.11.0-linux-armv6l.tar.gz --strip 1 -C /
            rm -rf /tmp/node-v6.11.0-linux-armv6l.tar.gz
            sudo ln -s /bin/node /bin/nodejs
        else
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install nodejs -y
        fi
    fi
fi

BASE_DIR="$LAST_BASE"
