#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Install hostapd and dnsmasq to run IEEE 802.11 Access Point
if ! [ "$(which hostapd)" ] || ! [ "$(dnsmasq)" ]; then
    sudo apt-get update
    sudo apt-get install hostapd dnsmasq radvd -y
fi

# Configure wlan0 interface
sudo cp /etc/network/interfaces /etc/network/interfaces.backup
START=$(grep -n "allow-hotplug wlan0" /etc/network/interfaces | awk '{ print $1 }' FS=':')
END=$(expr $START + 3)
sudo sed -i "${START},${END}d" /etc/network/interfaces
echo "" | sudo tee --append /etc/network/interfaces > /dev/null
echo "allow-hotplug wlan0" | sudo tee --append /etc/network/interfaces > /dev/null
echo "iface wlan0 inet static" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    address 10.0.0.1" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    netmask 255.255.255.0" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    network 10.0.0.0" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    broadcast 10.0.0.255" | sudo tee --append /etc/network/interfaces > /dev/null
echo "iface wlan0 inet6 static" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    address fdfc::2" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    netmask 64" | sudo tee --append /etc/network/interfaces > /dev/null

# Enable packet forwarding
sudo cp /etc/sysctl.conf /etc/sysctl.conf.backup
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sudo sed -i 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/' /etc/sysctl.conf

# Get network name and password
APSSID=$(sudo grep -m 1 '"ipv6"' /etc/cjdroute.conf | awk '{ print $2 }' | sed 's/[",]//g' | sed 's/.*:/tomesh-/g')
while [ "${#APPASS}" -lt 8 ] || [ "${#APPASS}" -gt 63 ]; do
    read -p "Set WPA2-PSK password for WiFi Access Point (8-63 characters): " APPASS;
done

# Configure network with hostapd
sudo cp "$BASE_DIR/nat.sh" /etc/hostapd/nat.sh
sudo cp "$BASE_DIR/hostapd.conf" /etc/hostapd/hostapd.conf
sudo echo "ssid=$APSSID" | sudo tee --append /etc/hostapd/hostapd.conf > /dev/null
sudo echo "wpa_passphrase=$APPASS" | sudo tee --append /etc/hostapd/hostapd.conf > /dev/null

# Configure DHCP with dnsmasq
sudo cp /etc/dnsmasq.conf /etc/dnsmasq.conf.backup
sudo cp "$BASE_DIR/dnsmasq.conf" /etc/dnsmasq.conf
sudo cp /etc/dhcpcd.conf /etc/dhcpcd.conf.backup
sudo echo "" | sudo tee --append /etc/dhcpcd.conf > /dev/null
sudo echo "denyinterfaces wlan0" | sudo tee --append /etc/dhcpcd.conf > /dev/null

# Configure IPv6 router advertisement with radvd
sudo cp "$BASE_DIR/radvd.conf" /etc/radvd.conf

# Enable hostapd service
sudo cp "$BASE_DIR/hostapd.service" /etc/systemd/system/hostapd.service
sudo systemctl enable hostapd
