#!/usr/bin/env bash

set -e


BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if ! [ "$(which confget)" ]; then
   sudo apt-get install confget
fi

# Install hostapd and dnsmasq to run IEEE 802.11 Access Point
if ! [ "$(which hostapd)" ] || ! [ "$(which dnsmasq)" ] || ! [ "$(which iptables)" ]; then
    sudo apt-get install hostapd radvd iptables -y
fi

APSSID=$(sudo grep -m 1 '"ipv6"' /etc/cjdroute.conf | awk '{ print $2 }' | sed 's/[",]//g' | sed "s/.*:/$MESH_NAME-/g")

read -p "Use WPA-EAP (Y) or WPA2-PSK (n) for WiFi Access Point $APSSID? " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Nn]$ ]]; then
    USE_EAP=false
    while [ "${#APPASS}" -lt 8 ] || [ "${#APPASS}" -gt 63 ]; do
        read -p "Set WPA2-PSK password (8-63 characters): " APPASS;
    done
else
    USE_EAP=true
    while [ "${#APPASS}" -lt 8 ] || [ "${#APPASS}" -gt 63 ]; do
        read -p "Set WPA-EAP password (8-63 characters) for user \"guest\": " APPASS;
    done
fi

sudo cp $BASE_DIR/75-lan-bridge.netdev /etc/systemd/network/75-lan-bridge.netdev
sudo cp $BASE_DIR/75-lan-bridge.network /etc/systemd/network/75-lan-bridge.network

sudo cp $BASE_DIR/95-wlan-hostap.link /etc/systemd/network/95-wlan-hostap.link
sudo sed -i "s/##SSID##/$APSSID/g" "/etc/systemd/network/95-wlan-hostap.link"

sudo cp $BASE_DIR/95-wlan-hostap.network /etc/systemd/network/95-wlan-hostap.network
if [ "$USE_EAP" = true ]; then
    sudo cp $BASE_DIR/wpa-eap/hostapd.template.conf /etc/hostapd/hostapd.template.conf
    sudo cp "$BASE_DIR/wpa-eap/hostapd.eap_user" /etc/hostapd/hostapd.eap_user
    sudo sed -i "s/##WPATYPE##/EAP/g" "/etc/systemd/network/95-wlan-hostap.link"
    sudo echo "\"guest\" MSCHAPV2 \"$APPASS\" [2]" | sudo tee --append /etc/hostapd/hostapd.eap_user > /dev/null

    cp -r "$BASE_DIR/wpa-eap/certs" "$BASE_DIR/tmp"
    /bin/bash "$BASE_DIR/tmp/bootstrap"
    sudo cp "$BASE_DIR/tmp/ca.pem" /etc/hostapd/ca.pem
    sudo cp "$BASE_DIR/tmp/server.pem" /etc/hostapd/server.pem
    rm -rf "$BASE_DIR/tmp"

else
    sudo cp $BASE_DIR/wpa-psk/hostapd.template.conf /etc/hostapd/hostapd.template.conf
    sudo sed -i "s/##WPATYPE##/PSK/g" "/etc/systemd/network/95-wlan-hostap.link"
    sudo sed -i "s/##PSK##/$APPASS/g" "/etc/systemd/network/95-wlan-hostap.link"

fi

sudo cp $BASE_DIR/50-hostapd.rules /etc/udev/rules.d/50-hostapd.rules 


sudo cp $BASE_DIR/hostapd.template /usr/local/sbin/hostapd.template
sudo chmod 744 /usr/local/sbin/hostapd.template

sudo cp $BASE_DIR/hostapd\@.service /etc/systemd/system/hostapd\@.service  

sudo cp "$BASE_DIR/hostapd.nat" /usr/local/sbin/hostapd.nat
sudo chmod 744 /usr/local/sbin/hostapd.nat

sudo cp $BASE_DIR/radvd.conf "/etc/radvd.conf"
