#!/usr/bin/env bash

set -e

sudo rm -rf  /etc/systemd/network/75-lan-bridge.netdev
sudo rm -rf  /etc/systemd/network/75-lan-bridge.network


sudo rm -rf /etc/systemd/network/95-wlan-hostap.link
sudo rm -rf /etc/systemd/network/95-wlan-hostap.network
sudo rm -rf /etc/udev/rules.d/50-hostapd.rules 
sudo rm -rf /etc/hostapd/hostapd.template.conf
sudo rm -rf /usr/local/sbin/hostapd.template
sudo rm -rf /etc/systemd/system/hostapd\@.service  
sudo rm -rf /etc/hostapd/hostapd.sh
sudo rm -rf "/etc/radvd.conf"
