#!/usr/bin/env bash

set -e

GO_NODE_EXPORTER_VERSION=0.14.0

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Download and install IPFS
mkdir "$BASE_DIR/tmp"

wget "https://github.com/prometheus/node_exporter/releases/download/v${GO_NODE_EXPORTER_VERSION}/node_exporter-${GO_NODE_EXPORTER_VERSION}.linux-armv6.tar.gz" -O "$BASE_DIR/tmp/go-node_exporter.tar.gz"
tar xvfz "$BASE_DIR/tmp/go-node_exporter.tar.gz" -C "$BASE_DIR/tmp" --strip 1

sudo cp "$BASE_DIR/tmp/node_exporter" /usr/local/bin/node_exporter
sudo chown root:staff /usr/local/bin/node_exporter
rm -rf "$BASE_DIR/tmp"

# Configure systemd to start ipfs-daemon.service on system boot
sudo cp "$BASE_DIR/node_exporter-daemon.service" /lib/systemd/system/node_exporter.service
sudo systemctl daemon-reload
sudo systemctl enable node_exporter.service
