#!/usr/bin/env bash

set -e

H_NTP_SERVER="fc4d:c8e5:9efe:9ac2:8e72:fcf7:6ce8:39dc"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Install NTP
if [ ! -x "$(command -v ntpd)" ]; then
    sudo apt-get install ntp -y
fi

# Configure Hyperboria NTP
sudo sed -i '/pool /d' /etc/ntp.conf
echo "pool -6 ${H_NTP_SERVER} iburst" | sudo tee --append /etc/ntp.conf > /dev/null
