#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MESH_NAME=$(confget -f /etc/mesh.conf -s general "mesh-name")

sudo apt-get install -y iw 

# Install bring-up script for the Mesh Ad-hoc interface to /usr/bin
cp "$BASE_DIR/mesh-adhoc" "/tmp/mesh-adhoc"
sed -i "s/MESH_NAME/$MESH_NAME/g" "/tmp/mesh-adhoc"
sudo mv "/tmp/mesh-adhoc" "/usr/bin/mesh-adhoc"

# Configure systemd to start mesh-adhoc.service on system boot
sudo cp "$BASE_DIR/mesh-adhoc.service" /etc/systemd/system/mesh-adhoc.service
sudo chmod 644 /etc/systemd/system/mesh-adhoc.service
sudo systemctl daemon-reload
sudo systemctl enable mesh-adhoc.service
