#!/usr/bin/env bash

set -e

mesh_name=$(confget -f /etc/mesh.conf -s general "mesh-name")
frequency=$(confget -f /etc/mesh.conf -s general "frequency")
ipv4=$(confget -f /etc/mesh.conf -s general "ipv4")

if [ -z "$frequency" ]; then
  frequency=2412
fi
# Select physical device that supports IBSS Ad-hoc
mesh_dev=$(confget -f /etc/mesh.conf -s general "ibss-dev")
if [ -z "$mesh_dev" ]; then
  mesh_dev="$(iw dev | grep Interface | grep -v wlan-ap | head -n 1 | awk '{print $2}')"
fi

# Set wireless regulatory domain
sudo iw reg set CA

# Is it safe to stop wpa_supplicant. Is AP running
if [ ! -d /sys/class/net/wlan-ap ]; then
  # Kill wpa_supplicant with sometimes conflicts with IBSS Ad-Hoc
  sudo killall wpa_supplicant || true
fi

# Shut down the mesh_dev interface
sudo ifconfig $mesh_dev down

# Convert mesh_dev to IBSS Ad-hoc interface
sudo iw $mesh_dev set type ibss

# Bring up the mesh_dev interface
sudo ifconfig $mesh_dev up

# Optionally assign IPv4 address to the mesh_dev interface
if ! [ -z "$ipv4" ]; then
    sudo ifconfig $mesh_dev $ipv4
fi

# Join the mesh network
# To join radio in HT40+ htmode (enable 802.11n rates) add HT40+ to end of this line
sudo iw dev $mesh_dev ibss join $mesh_name $frequency

# Make a local-link ip out of yggdrasil ip if $mesh_dev does not have a local-link ip
if [ ! -z "$(which yggdrasilctl)" ]; then
  if [ -z "$(ip addr show dev $mesh_dev | grep inet6\ fe)" ]; then
	  ip="$(sudo yggdrasilctl getSelf | grep "IPv6 address" | awk '{print $3}' | cut -d ":" -f5-8)"
	  ip address add dev $mesh_dev scope link fe80::${ip}/64
  fi
fi

# Restart cjdns
sudo killall cjdroute
