#!/usr/bin/env bash

set -e

# Replace placeholders with dynamic info
sed -i -e "s/REPO/$(git remote get-url origin | awk -F / '{print $5}'| cut -d '.' -f1)/g" nodeinfo.json
sed -i -e "s/BRANCH/$(git rev-parse --abbrev-ref HEAD)/g" nodeinfo.json
sed -i -e "s/COMMIT/$(git rev-parse HEAD)/g" nodeinfo.json
sed -i -e "s/INSTALLED/$(date)/g" nodeinfo.json

sed -i -e "s/KEY/$(cat /etc/cjdroute.conf | jq '.publicKey')/g" nodeinfo.json
sed -i -e "s/ORG/$MESH_NAME/g" nodeinfo.json

# Only adding IPFS for now, more to come later
if [[ "$SUPPORT_IPFS" == "true" ]] && [ ! -z "$WITH_IPFS" -a "$WITH_IPFS" == "true" ]; then
        sed -i -e 's/SERVICES/"ipfs":{"version":"'"$(ipfs --version | awk '{ print $3 }')"'","ID":'"$(ipfs id | jq '.ID')}"/g nodeinfo.json
else
    sed -i -e 's/SERVICES//g' # Leave it empty
fi
 
sudo cp nodeinfo.json /var/www/html
