#!/usr/bin/env bash

set -e

LAST_BASE="$BASE_DIR"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sudo mkdir -p /opt/tomesh/nodeinfo.d

sudo cp $BASE_DIR/nodeinfo.json /opt/tomesh
sudo cp $BASE_DIR/nodeinfo-update.sh /usr/local/bin/nodeinfo-update.sh

BASE_DIR="$LAST_BASE"
