#!/bin/bash

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sudo apt-get install libiw-dev

# Copied from https://github.com/bmx-routing/bmx7#bmx7
mkdir $BASE_DIR/tmp

(
  wget https://tls.mbed.org/download/mbedtls-2.4.0-gpl.tgz -O "$BASE_DIR/tmp/mbedtls-2.4.0-gpl.tgz"
  cd "$BASE_DIR/tmp" || exit
  tar xzvf mbedtls-2.4.0-gpl.tgz
  cd mbedtls-2.4.0 || exit
  make
  sudo make install
)

(
  cd "$BASE_DIR/tmp" || exit
  # compile bmx7 with: make EXTRA_CFLAGS="-DCRYPTLIB=MBEDTLS_2_4_0"
  git clone https://github.com/bmx-routing/bmx7.git
  cd bmx7 || exit
  make EXTRA_CFLAGS="-DCRYPTLIB=MBEDTLS_2_4_0"
  sudo make install 
)

rm -rf "$BASE_DIR/tmp"

sudo cp "$BASE_DIR/bmx7.service" /etc/systemd/system/bmx7.service

sudo systemctl daemon-reload
sudo systemctl enable bmx7.service
sudo systemctl start bmx7.service
