#!/usr/bin/env bash

# Convert existing yggdrasil config to json from hjson

# Detect if there is a # as a first character of the file.
# If it is then its proably a hjson and needs to be converted into json
if [ ! -z "$(tr -d ' \t\r\f' < /etc/yggdrasil.conf   | grep -i "^[#]")"  ]; then
    sudo mv /etc/yggdrasil.conf /etc/yggdrasil.conf.orig
    sudo yggdrasil -useconffile /etc/yggdrasil.conf.orig -normaliseconf -json | sudo tee /etc/yggdrasil.conf > /dev/null
fi

if [ -e /etc/yggdrasil.iptunnel.server ]; then
    # Add each client to yggdrasil iptunnel allowed connections
    while read -r PUBLIC_KEY IP_ADDR IP6_ADDR; do
        if [[ "${PUBLIC_KEY}" =~ ^[0-z]{64} ]]; then
            IPv4Destinations="${IPv4Destinations} \"${IP_ADDR}/32\": \"${PUBLIC_KEY}\","
            if [[ ! -z "${IP6_ADDR}" ]]; then
               IPv6Destinations="${IPv6Destinations} \"${IP6_ADDR}/128\": \"${PUBLIC_KEY}\","
            fi
        fi
    done < /etc/yggdrasil.iptunnel.server

    # Trim last ,
    IPv4Destinations="${IPv4Destinations%?}"
    IPv6Destinations="${IPv6Destinations%?}"

    IPv4Sources="0.0.0.0/0"

    if [[ ! -z "${IPv6Destinations}" ]]; then
        IPv6Sources="0.0.0.0/0"
    fi
elif [ -e /etc/yggdrasil.iptunnel.client ]; then
    # Add each server to yggdrasil iptunnel connect-to's
    while read -r PUBLIC_KEY IP_ADDR IP6_ADDR; do
        if [[ "${PUBLIC_KEY}" =~ ^[0-z]{64} ]]; then
            if [[ ! -z "${IP6_ADDR}" ]]; then
               IPv6Destinations="\"::/0\": \"${PUBLIC_KEY}\""
               IPv6Sources="${IP6_ADDR}/128"
            fi
            IPv4Destinations="\"0.0.0.0/0\": \"${PUBLIC_KEY}\""
            IPv4Sources="${IP_ADDR}/32"
        fi
    done < /etc/yggdrasil.iptunnel.client
 fi

# Check if there are values to set in the new config file
if [ ! -z "$IPv4Sources" ];then
    # Re-write tunnel routing
    sudo jq 'del(.TunnelRouting)' /etc/yggdrasil.conf > /tmp/yggdrasil.conf
    sudo jq '.TunnelRouting.IPv4Sources = "__IPv4Sources__"' /tmp/yggdrasil.conf > /tmp/yggdrasil-edit.conf && sudo mv /tmp/yggdrasil-edit.conf /tmp/yggdrasil.conf
    sudo jq '.TunnelRouting.IPv4Destinations = "__IPv4Destinations__"' /tmp/yggdrasil.conf > /tmp/yggdrasil-edit.conf && sudo mv /tmp/yggdrasil-edit.conf /tmp/yggdrasil.conf
    sudo sed -i "s#\"__IPv4Sources__\"#[\"$IPv4Sources\"]#" /tmp/yggdrasil.conf
    sudo sed -i "s#\"__IPv4Destinations__\"#\{$IPv4Destinations\}#" /tmp/yggdrasil.conf

    if [[ ! -z "${IPv6Destinations}" ]]; then
      sudo jq '.TunnelRouting.IPv6Sources = "__IPv6Sources__"' /tmp/yggdrasil.conf > /tmp/yggdrasil-edit.conf && sudo mv /tmp/yggdrasil-edit.conf /tmp/yggdrasil.conf
      sudo jq '.TunnelRouting.IPv6Destinations = "__IPv6Destinations__"' /tmp/yggdrasil.conf > /tmp/yggdrasil-edit.conf && sudo mv /tmp/yggdrasil-edit.conf /tmp/yggdrasil.conf
      sudo sed -i "s#\"__IPv6Sources__\"#[\"$IPv6Sources\"]#" /tmp/yggdrasil.conf
      sudo sed -i "s#\"__IPv6Destinations__\"#\{$IPv6Destinations\}#" /tmp/yggdrasil.conf
   fi
      sudo jq '.TunnelRouting.Enable = true' /tmp/yggdrasil.conf > /tmp/yggdrasil-edit.conf && sudo mv /tmp/yggdrasil-edit.conf /tmp/yggdrasil.conf
      sudo mv /tmp/yggdrasil.conf /etc/yggdrasil.conf
fi

