#!/usr/bin/env bash

# Enable forwarding for ipv4 and ipv6
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

SUBNET4="10.10.0."

# Give yggdrasil enough time to create an ygg0 interface before we start adding routes
sleep 5

if [ -e /etc/yggdrasil.iptunnel.server ]; then
    # Add route for cjdns ygg0 interface
    sudo route add -net "${SUBNET4}0/24" ygg0 || true

    # If no NAT (masquarading) being done, start doing it
    if [ -z "$(sudo iptables -L POSTROUTING -v -n -t nat  | grep MASQUERADE)" ]; then
        sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    fi
# Configure as yggdrasil iptunnel client if client file is present (this is simply a newline-separated list
# of cjdns public keys in /etc/yggdrasil.iptunnel.client, each key indicating an iptunnel exit server)
elif [ -e /etc/yggdrasil.iptunnel.client ]; then
    # Add each server to yggdrasil iptunnel connect-to's
    while read -r PUBLIC_KEY ASSIGNED_IP; do
        if [[ "${PUBLIC_KEY}" =~ ^[0-z]{64} ]]; then
            sudo ip addr add dev ygg0 ${ASSIGNED_IP}/32
        fi
    done < /etc/yggdrasil.iptunnel.client

    # Remove NAT from eth0 if it exists
    sudo iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE || true

    # Route NAT traffic through to yggdrasil ygg0 interface to use iptunnel exit server
    sudo iptables -t nat -A POSTROUTING -o ygg0 -j MASQUERADE

    # Special hack to change default route without removing original one
    sudo route add  -net 0.0.0.0/1 ygg0
    sudo route add  -net 128.0.0.0/1 ygg0
fi
