#!/usr/bin/env bash

set -e

H_DNS_SERVER_0="fc4d:c8e5:9efe:9ac2:8e72:fcf7:6ce8:39dc"
H_DNS_SERVER_1="fc6e:691e:dfaa:b992:a10a:7b49:5a1a:5e09"
H_DNS_SERVER_2="fc16:b44c:2bf9:467:8098:51c6:5849:7b4f"

# Configure Hyperboria DNS
sudo sed -i '/dns-nameservers /d' /etc/network/interfaces
echo "" | sudo tee --append /etc/network/interfaces > /dev/null
echo "dns-nameservers ${H_DNS_SERVER_0} ${H_DNS_SERVER_1} ${H_DNS_SERVER_2}" | sudo tee --append /etc/network/interfaces > /dev/null
