#!/usr/bin/env bash

set -e

H_DNS_SERVER_0="fc4d:c8e5:9efe:9ac2:8e72:fcf7:6ce8:39dc"
H_DNS_SERVER_1="fc16:b44c:2bf9:467:8098:51c6:5849:7b4f"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configure Hyperboria DNS
sudo sed -i '/dns-nameservers /d' /etc/network/interfaces
sudo echo "dns-nameservers ${H_DNS_SERVER_0} ${H_DNS_SERVER_1}" >> /etc/network/interfaces