#!/usr/bin/env bash

set -e

# Uninstall yrd
sudo systemctl disable yrd 2>/dev/null || true
sudo systemctl stop yrd 2>/dev/null || true
sudo systemctl daemon-reload
sudo pip3 uninstall -y yrd || true
sudo apt-get remove -y python3-argh python3-pip python3-requests python3
sudo rm -f /etc/systemd/system/yrd.service || true
sudo rm -f /usr/local/bin/yrd || true
