#!/bin/sh
if [ -z "$1" ] && [ -z "$2" ]; then
   echo Syntax 
   echo create Device User
   echo Device - Device to format and mount
   echo User - User running ipfs that the repo will be moved to
   exit 0
fi

mkfs.ext3 /dev/$1
service ipfs stop
e2label  /dev/$1 ipfs-data
mkdir /mnt/ipfs-data
echo "LABEL=ipfs-data  /mnt/ipfs-data ext3  defaults,noatime  0  0" >> /etc/fstab
mount /mnt/ipfs-data
mv /home/$2/.ipfs /mnt/ipfs-data/
ln -s /mnt/ipfs-data/.ipfs /home/$2/.ipfs
service ipfs start
