#!/bin/bash

sudo apt-get remove -y netcat-traditional || true
sudo apt-get remove -y netcat6 || true
sudo apt-get remove -y ncat || true
sudo apt-get remove -y netcat || true
sudo apt-get install -y netcat-openbsd
