#!/usr/bin/env bash

set -e

if [ ! -x "$(command -v nginx)" ] || [ ! -d "/etc/nginx/site-path-enabled" ]; then
    LAST_BASE="$BASE_DIR"
    BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    sudo apt-get install nginx -y

    sudo cp -f "$BASE_DIR/main.conf" /etc/nginx/sites-available/main.conf
    sudo ln -s /etc/nginx/sites-available/main.conf /etc/nginx/sites-enabled/main.conf || true
    sudo rm /etc/nginx/sites-enabled/default || true
    sudo mkdir /etc/nginx/site-path-enabled || true

    # Install welcome page
    sudo cp "$BASE_DIR/index.html" "/var/www/html/index.html"
    sudo sed -i "s/__NODENAME__/$NEWHOSTNAME/" "/var/www/html/index.html"

    BASE_DIR="$LAST_BASE"
    
fi
