#!/usr/bin/env bash

set -e

GO_IPFS_VERSION=v0.4.17

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Download and install IPFS
mkdir "$BASE_DIR/tmp"
wget "https://dist.ipfs.io/go-ipfs/${GO_IPFS_VERSION}/go-ipfs_${GO_IPFS_VERSION}_linux-arm.tar.gz" -O "$BASE_DIR/tmp/go-ipfs.tar.gz"
tar xvfz "$BASE_DIR/tmp/go-ipfs.tar.gz" -C "$BASE_DIR/tmp"
sudo cp "$BASE_DIR/tmp/go-ipfs/ipfs" /usr/local/bin/ipfs
sudo chown root:staff /usr/local/bin/ipfs
rm -rf "$BASE_DIR/tmp"

# Initialize IPFS
ipfs init

# Configure systemd to start ipfs.service on system boot
sudo cp "$BASE_DIR/ipfs.service" /etc/systemd/system/ipfs.service
sudo sed -i "s|__USER_HOME__|${HOME}|" /etc/systemd/system/ipfs.service
sudo systemctl daemon-reload
sudo systemctl enable ipfs.service
sudo systemctl start ipfs.service

# Configure HTTP to IPFS gateway
source "$BASE_DIR/../shared/nginx/install"
sudo cp "$BASE_DIR/ipfs-http-gateway.conf" /etc/nginx/site-path-enabled/ipfs-http-gateway.conf
sudo systemctl restart nginx.service

source "$BASE_DIR/../shared/nodeinfo/install"
sudo cp $BASE_DIR/nodeinfo-ipfs /opt/tomesh/nodeinfo.d/ipfs
sudo chmod + /opt/tomesh/nodeinfo.d/nodeinfo-ipfs.sh

# add cjdns bootstrap address
ipfs bootstrap add /ip6/fc6e:691e:dfaa:b992:a10a:7b49:5a1a:5e09/tcp/4001/ipfs/QmU6NeD2Uu34WKest1NZGvGmScLhN1zVo66K35GeE6Jft2

# Service to bootstrap neighboring cjdns nodes if no other ipfs is found

# Download dependencies
sudo apt-get install -y jq

# Move file
sudo cp $BASE_DIR/peer-ipfs-bootstrap/check-and-add-peers.sh /usr/local/bin/
sudo chmod +x /usr/local/bin/check-and-add-peers.sh

# Create file for data
sudo mkdir /var/lib/peer-ipfs-bootstrap
sudo touch /var/lib/peer-ipfs-bootstrap/peers.data
sudo chmod 777 /var/lib/peer-ipfs-bootstrap/peers.data

# Enable service
sudo cp $BASE_DIR/peer-ipfs-bootstrap/peer-ipfs-bootstrap.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable peer-ipfs-bootstrap.service
