#!/bin/bash

INACTIVE='\e[1;31m[INACTIVE]\e[0m'
ACTIVE='\e[1;32m[ACTIVE]\e[0m'

echo "   _                           _     "
echo "  | |_ ___  _ __ ___   ___ ___| |__  "
echo "  | __/ _ \| '_ \` _ \ / _ / __| '_ \ "
echo "  | || (_) | | | | | |  __\__ | | | |"
echo "   \__\___/|_| |_| |_|\___|___|_| |_|"

echo -e '---------------------------------------'
echo -e 'NODE'
if [ "$(iw dev mesh0 info | grep 'type mesh point')" ] && [ "$(iw dev mesh0 info | grep 'channel')" ]; then
        echo -e "Mesh Interface ............... $ACTIVE"
else
        echo -e "Mesh Interface ............. $INACTIVE"
fi
if [ $(systemctl status cjdns.service | grep 'Active: ' | awk '{ print $2 }') = 'active' ]; then
        echo -e "cjdns Service ................ $ACTIVE"
else
        echo -e "cjdns Service .............. $INACTIVE"
fi

echo -e '---------------------------------------'

echo -e 'PEERS'
nodejs ~/cjdns/tools/pingAll | grep '@' | sed 's/@.*//'

echo -e '---------------------------------------'
