#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Uninstall optional modules
source "$BASE_DIR/cjdns/uninstall"
source "$BASE_DIR/cjdns-iptunnel/uninstall"
source "$BASE_DIR/ssb/uninstall"
source "$BASE_DIR/mesh-point/uninstall"
source "$BASE_DIR/mesh-adhoc/uninstall"
source "$BASE_DIR/hostapd/uninstall"
source "$BASE_DIR/firewall/uninstall"
source "$BASE_DIR/ipfs/uninstall"
source "$BASE_DIR/prometheus-node-exporter/uninstall"
source "$BASE_DIR/prometheus-server/uninstall"
source "$BASE_DIR/grafana/uninstall"
source "$BASE_DIR/extra-tools/uninstall"
source "$BASE_DIR/watchdog/uninstall"
source "$BASE_DIR/yrd/uninstall"
source "$BASE_DIR/shared/nodeinfo/uninstall"
source "$BASE_DIR/nginx/uninstall"
source "$BASE_DIR/yggdrasil/uninstall"
source "$BASE_DIR/yggdrasil-iptunnel/uninstall"

sudo systemctl daemon-reload

sudo sed -i 's/service dnsmasq restart//' /etc/rc.local

# Uninstall status script
sudo rm -f /usr/local/bin/status

# Remove .bash_profile
rm -f ~/.bash_profile
