#!/bin/sh

set -e

sudo systemctl disable mesh.service
sudo rm -f /usr/bin/mesh
sudo rm -f /lib/systemd/system/mesh.service

sudo systemctl disable cjdns.service
sudo rm -f /usr/bin/cjdroute
sudo rm -f /lib/systemd/system/cjdns.service
sudo rm -f /lib/systemd/system/cjdns-resume.service
sudo rm -f /etc/cjdroute.conf
sudo rm -rf /opt/cjdns

sudo systemctl disable ipfs-daemon.service
sudo rm -f /usr/local/bin/ipfs
sudo rm -f /lib/systemd/system/ipfs-daemon.service
rm -rf /home/pi/.ipfs

sudo systemctl daemon-reload
