#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Uninstall cjdns
sudo systemctl disable cjdns.service 2>/dev/null
sudo systemctl stop cjdns.service 2>/dev/null || true
sudo rm -f /usr/bin/cjdroute
sudo rm -f /lib/systemd/system/cjdns.service
sudo rm -f /lib/systemd/system/cjdns-resume.service
sudo rm -rf /opt/cjdns

if [ -f "/etc/cjdroute.conf" ]; then
    echo "Found /etc/cjdroute.conf"
    read -p "Remove your cjdns identity (Y/n)? " RM_CJDNS_CONF;
    if [ "$RM_CJDNS_CONF" == "Y" ]; then
        echo "Removing /etc/cjdroute.conf"
        sudo rm -f /etc/cjdroute.conf
    else
        echo "Keeping /etc/cjdroute.conf"
    fi
fi

# Uninstall optional modules
source "$BASE_DIR/mesh-point/uninstall"
source "$BASE_DIR/hostapd/uninstall"
source "$BASE_DIR/ipfs/uninstall"

sudo systemctl daemon-reload
