#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sudo npm install scuttlebot -g --unsafe-perm
sudo apt-get install -y socat

currentUser=$USER

sudo cp "$BASE_DIR/ssb.service" /etc/systemd/system/ssb.service
sudo sed -i "s|__USER__|${currentUser}g" /etc/systemd/system/ssb.service

sudo systemctl daemon-reload
sudo systemctl enable ssb.service
sudo systemctl start ssb.service

# Wait for ssb identity to be created
sleep 3

sudo cp "$BASE_DIR/ssb-broadcast-service.sh" "/usr/local/bin/ssb-broadcast-service.sh"
sudo cp "$BASE_DIR/ssb-broadcast.service" /etc/systemd/system/ssb-broadcast.service
sudo sed -i "s|_USER_|${currentUser}|" /etc/systemd/system/ssb-broadcast.service

id=$(sbot whoami | grep id | awk -F "\"" '{print $4}' | sed 's/.ed25519//' | sed 's/@//')
sudo sed -i "s|__ID__|${id}|g" /etc/systemd/system/ssb-broadcast.service

sudo systemctl daemon-reload
sudo systemctl enable ssb-broadcast.service
