#!/usr/bin/env bash

set -e

# Uninstall cjdns
sudo systemctl disable cjdns.service 2>/dev/null || true
sudo systemctl stop cjdns.service 2>/dev/null || true
sudo rm -f /usr/bin/cjdroute
sudo rm -f /etc/systemd/system/cjdns.service
sudo rm -f /etc/systemd/system/cjdns-resume.service
sudo rm -rf /opt/cjdns

if [ -f "/etc/cjdroute.conf" ]; then
    echo "Found /etc/cjdroute.conf"
    read -p "Keep your cjdns identity (Y/n)? " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo -e "\e[1;31mRemoving /etc/cjdroute.conf\e[0m"
        sudo rm -f /etc/cjdroute.conf
    else
        echo -e "\e[1;32mKeeping /etc/cjdroute.conf\e[0m"
    fi
fi
