#!/usr/bin/env bash

set -e

NODE_EXPORTER_VERSION=0.17.0

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ARCH="$(uname -m)" 
case "$ARCH" in
  x86_64)
    ARCH="amd64"
  ;;
  i386 | i586 | i686 )
    ARCH="386"
  ;;
  armv7l)
    ARCH="armv7";
  ;;
  armv6l)
      ARCH="armv6";
  ;;
  aarch64)
    ARCH="arm64";
  ;;
  *)
    echo "Unknown Arch"
    exit 1
  ;;
esac

if [[ ! -f "/usr/local/bin/node_exporter" ]]; then
    mkdir "$BASE_DIR/tmp" || true
    wget "https://github.com/prometheus/node_exporter/releases/download/v${NODE_EXPORTER_VERSION}/node_exporter-${NODE_EXPORTER_VERSION}.linux-${ARCH}.tar.gz" -O "$BASE_DIR/tmp/node_exporter.tar.gz"
    tar xvfz "$BASE_DIR/tmp/node_exporter.tar.gz" -C "$BASE_DIR/tmp" --strip 1
    sudo cp "$BASE_DIR/tmp/node_exporter" /usr/local/bin/node_exporter
    sudo chown root:staff /usr/local/bin/node_exporter
    rm -rf "$BASE_DIR/tmp"
fi

sudo mkdir /var/lib/node_exporter/ || true
sudo mkdir /opt/tomesh/ || true
sudo cp "$BASE_DIR/nodestats-tomesh.py" "/opt/tomesh/nodestats-tomesh.py"

# Configure systemd to start prometheus-node-exporter.service on system boot
sudo cp "$BASE_DIR/prometheus-node-exporter.service" /etc/systemd/system/prometheus-node-exporter.service
sudo cp "$BASE_DIR/node-exporter-tomesh.service" /etc/systemd/system/node-exporter-tomesh.service

apt-get install python2 libpython2-stdlib
pip install 
sudo systemctl daemon-reload
sudo systemctl enable prometheus-node-exporter.service
sudo systemctl start prometheus-node-exporter.service
sudo systemctl enable node-exporter-tomesh.service
sudo systemctl start node-exporter-tomesh.service
