#!/usr/bin/env bash

set -e

NODE_EXPORTER_VERSION=0.14.0

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Download and install Prometheus Node Exporter
ARM_VERSION=v7
if uname -m | grep -Eq ^armv6; then
    ARM_VERSION=v6
elif uname -m | grep -q aarch64; then
    ARM_VERSION=64
fi
if [[ ! -f "/usr/local/bin/node_exporter" ]]; then
    mkdir "$BASE_DIR/tmp" || true
    wget "https://github.com/prometheus/node_exporter/releases/download/v${NODE_EXPORTER_VERSION}/node_exporter-${NODE_EXPORTER_VERSION}.linux-arm${ARM_VERSION}.tar.gz" -O "$BASE_DIR/tmp/node_exporter.tar.gz"
    tar xvfz "$BASE_DIR/tmp/node_exporter.tar.gz" -C "$BASE_DIR/tmp" --strip 1
    sudo cp "$BASE_DIR/tmp/node_exporter" /usr/local/bin/node_exporter
    sudo chown root:staff /usr/local/bin/node_exporter
    rm -rf "$BASE_DIR/tmp"
fi

sudo mkdir /var/lib/node_exporter/ || true
sudo mkdir /opt/tomesh/ || true
sudo cp "$BASE_DIR/nodestats-tomesh.py" "/opt/tomesh/nodestats-tomesh.py"

# Configure systemd to start prometheus-node-exporter.service on system boot
sudo cp "$BASE_DIR/prometheus-node-exporter.service" /etc/systemd/system/prometheus-node-exporter.service
sudo cp "$BASE_DIR/node-exporter-tomesh.service" /etc/systemd/system/node-exporter-tomesh.service

sudo systemctl daemon-reload
sudo systemctl enable prometheus-node-exporter.service
sudo systemctl start prometheus-node-exporter.service
sudo systemctl enable node-exporter-tomesh.service
sudo systemctl start node-exporter-tomesh.service
