#!/usr/bin/env bash

set -e

YGGDRASIL_VERSION=0.2.6

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Download and install yggdrasil routing engine

ARM_VERSION=armhf
if uname -m | grep -q aarch64; then
    ARM_VERSION=arm64
fi

if [[ ! -f "/usr/bin/yggdrasil" ]]; then
    mkdir "$BASE_DIR/tmp"
    wget "https://236-115685026-gh.circle-artifacts.com/0/yggdrasil-${YGGDRASIL_VERSION}-${ARM_VERSION}.deb" -O "$BASE_DIR/tmp/yggdrasil.deb"
    sudo dpkg -i "$BASE_DIR/tmp/yggdrasil.deb"
fi
